# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bbd7603dc077ea00c6197082015453fb7790b53ce1957baea96c3b22e7f45c03612f0efa003faf359356373dcc791c6266e6a0540cba5e03104c8dafd54ad36

# Use different runs of `rake secret` for development and test
test:
  secret_key_base: bf04877bfcbb04b7f806ec07f8b14e13469208f8a234f3d141b48bc1354677826e61620e445e06be23dd4a086679cdfab21dd383e91d85eb1a9c87fc87be049e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 305334d9095d33df75e0a8eb5bfe4cd702eaea037137bac8efdaf27cbb7eb29528660b6f76fc2d92d137983893a4257d4bbd4e63dd4932e19628f6a16f5853f9
